[workspace]
members = [
    "bam-scan",
    "bam-unique",
    "bam-collect-doc",
    "bam-collect-pesr",
    "lib-common",
    "lib-config",
    "vcf-annotate",
    "vcf-cluster",
    "vcf-standardize",
]
